apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  replicas: {{ .Values.replicas.worker }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: worker
    spec:
      containers:
      - name: worker
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command: ["odoo", "--workers=0", "--max-cron-threads=0"]
        envFrom:
        - secretRef:
            name: {{ .Release.Name }}-secret
