apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-filestore
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.filestore.storageClass }}
  resources:
    requests:
      storage: {{ .Values.filestore.size }}
